### ISSUE TITLE
OSError: mysql_config not found -- Manjaro || Ubuntu

### ISSUE THREAD

**Issue by NaveenThurimerla** [NaveenThurimerla/music-box#2]
```
- >  cwd: /tmp/pip-install-hk2p9liv/mysqlclient/
- >     Complete output (12 lines):
- >     /bin/sh: mysql_config: command not found
- >     /bin/sh: mariadb_config: command not found
- >     /bin/sh: mysql_config: command not found
- >     Traceback (most recent call last):
- >       File "<string>", line 1, in <module>
- >       File "/tmp/pip-install-hk2p9liv/mysqlclient/setup.py", line 15, in <module>
- >         metadata, options = get_config()
- >       File "/tmp/pip-install-hk2p9liv/mysqlclient/setup_posix.py", line 65, in get_config
- >         libs = mysql_config("libs")
- >       File "/tmp/pip-install-hk2p9liv/mysqlclient/setup_posix.py", line 31, in mysql_config
- >         raise OSError("{} not found".format(_mysql_config_path))
- >     OSError: mysql_config not found
- > 
```

**Comment by NaveenThurimerla** [comment]
**Ubuntu** : 
`sudo apt-get install libmysqlclient-dev`
